[project]
name = "richmail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "email-validator>=2.3.0",
    "mysql-connector-python>=9.5.0",
    "python-dotenv>=1.2.1",
]
